# Generated by Django 5.1.4 on 2026-05-18 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste'), ('venda', 'Venda'), ('devolucao', 'Devolução')], max_length=20, verbose_name='Tipo')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('quantidade_anterior', models.IntegerField(default=0, verbose_name='Qtd Anterior')),
                ('quantidade_posterior', models.IntegerField(default=0, verbose_name='Qtd Posterior')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-created_at'],
            },
        ),
    ]
