# Generated by Django 5.1.4 on 2026-05-18 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoGlobal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ean', models.CharField(max_length=13, unique=True, verbose_name='EAN')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('imagem', models.URLField(blank=True, verbose_name='URL Imagem')),
                ('fonte', models.CharField(blank=True, help_text='OpenFoodFacts, BarcodeLookup, etc', max_length=50, verbose_name='Fonte')),
            ],
            options={
                'verbose_name': 'Produto Global',
                'verbose_name_plural': 'Produtos Globais',
                'ordering': ['nome'],
            },
        ),
    ]
