# Generated by Django 5.1.4 on 2026-05-18 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('direcao', models.CharField(choices=[('upload', 'Upload (PDV -> Cloud)'), ('download', 'Download (Cloud -> PDV)')], max_length=20)),
                ('registros_total', models.IntegerField(default=0)),
                ('registros_sucesso', models.IntegerField(default=0)),
                ('registros_erro', models.IntegerField(default=0)),
                ('duracao_ms', models.IntegerField(default=0)),
                ('detalhes', models.JSONField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
                ('pdv_terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.pdvterminal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo_operacao', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('tabela', models.CharField(max_length=100)),
                ('registro_uuid', models.UUIDField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('synced', 'Sincronizado'), ('error', 'Erro')], default='pending', max_length=20)),
                ('tentativas', models.IntegerField(default=0)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
                ('pdv_terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.pdvterminal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
