# Generated by Django 5.1.4 on 2026-05-18 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, verbose_name='Código de Barras')),
                ('sem_codigo_barras', models.BooleanField(default=False, verbose_name='Sem Código de Barras')),
                ('codigo_interno', models.CharField(blank=True, help_text='Gerado automaticamente para produtos sem código de barras', max_length=20, verbose_name='Código Interno')),
                ('valor_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Compra (R$)')),
                ('lucro_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Lucro (%)')),
                ('valor_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Venda (R$)')),
                ('comprado_em_caixa', models.BooleanField(default=False, verbose_name='Comprado em Caixa')),
                ('valor_caixa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Caixa (R$)')),
                ('qtd_itens_caixa', models.IntegerField(blank=True, null=True, verbose_name='Quantidade na Caixa')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('estoque_minimo', models.IntegerField(default=5, verbose_name='Estoque Mínimo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('favorito', models.BooleanField(default=False, verbose_name='Favorito')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lucro_percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Histórico de Preços',
                'ordering': ['-created_at'],
            },
        ),
    ]
