# Generated by Django 5.1.4 on 2026-05-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=10, verbose_name='Estoque Mínimo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qtd_itens_caixa',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Quantidade na Caixa (ou Kilos)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantidade em Estoque'),
        ),
    ]
