# Generated by Django 5.1.4 on 2026-05-18 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('produtos', '0003_alter_produto_estoque_minimo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embalagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(help_text='Ex: Caixa de Ovos, Saco de Batata', max_length=100, verbose_name='Nome da Embalagem')),
                ('quantidade_itens', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade Padrão (Unidades/Kilos)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Embalagem',
                'verbose_name_plural': 'Embalagens',
                'ordering': ['nome'],
            },
        ),
    ]
