# Generated by Django 5.1.4 on 2026-05-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_embalagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('un', 'Unidade (un)'), ('kg', 'Quilos (kg)'), ('dz', 'Dúzia (dz)'), ('fd', 'Fardo (fd)'), ('cx', 'Caixa (cx)'), ('lt', 'Litro (lt)')], default='un', max_length=10, verbose_name='Unidade de Medida'),
        ),
    ]
