# Generated by Django 5.1.4 on 2026-05-18 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteLocal',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('nfc_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(blank=True, max_length=128)),
                ('api_cloud_url', models.CharField(default='http://localhost:8000', max_length=255)),
                ('ultimo_sync', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoLocal',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_interno', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidade_medida', models.CharField(default='un', max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='VendaLocal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(max_length=20)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='local_pdv.clientelocal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemVendaLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local_pdv.produtolocal')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='local_pdv.vendalocal')),
            ],
        ),
    ]
