# Generated by Django 5.1.4 on 2026-05-26 21:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_pdv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoCaixaLocal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operador_username', models.CharField(max_length=150)),
                ('abertura', models.DateTimeField(auto_now_add=True)),
                ('fechamento', models.DateTimeField(blank=True, null=True)),
                ('valor_abertura', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_fechamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='aberta', max_length=20)),
                ('synced', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-abertura'],
            },
        ),
        migrations.AddField(
            model_name='vendalocal',
            name='sessao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='local_pdv.sessaocaixalocal'),
        ),
    ]
