# Generated by Django 5.1.4 on 2026-05-28 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_pdv', '0002_sessaocaixalocal_vendalocal_sessao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configlocal',
            name='mp_access_token',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.CreateModel(
            name='PagamentoPix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mp_payment_id', models.CharField(max_length=100, verbose_name='Payment ID (MP)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_code', models.TextField(blank=True, default='', verbose_name='PIX Copia e Cola')),
                ('qr_code_base64', models.TextField(blank=True, default='', verbose_name='QR Code Base64')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_pix', to='local_pdv.vendalocal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
