# Generated by Django 4.2.30 on 2026-05-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_pdv', '0003_configlocal_mp_access_token_pagamentopix'),
    ]

    operations = [
        migrations.AddField(
            model_name='configlocal',
            name='empresa_cnpj',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='configlocal',
            name='empresa_endereco',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='configlocal',
            name='empresa_nome',
            field=models.CharField(blank=True, default='Empresa PDV', max_length=200),
        ),
        migrations.AddField(
            model_name='configlocal',
            name='empresa_telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
