# Generated by Django 4.2.30 on 2026-05-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_pdv', '0004_configlocal_empresa_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendalocal',
            name='status',
            field=models.CharField(default='finalizada', max_length=20),
        ),
    ]
