# Generated by Django 4.2.30 on 2026-05-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_pdv', '0005_vendalocal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaocaixalocal',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
