# Generated by Django 5.1.4 on 2026-05-27 16:18

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_empresa_config_impressao_tamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEfi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, default='', help_text='Obtido no painel da Efi ao criar sua aplicacao.', max_length=200, verbose_name='Client ID (Efi)')),
                ('client_secret', models.CharField(blank=True, default='', help_text='Obtido no painel da Efi ao criar sua aplicacao.', max_length=200, verbose_name='Client Secret (Efi)')),
                ('sandbox', models.BooleanField(default=True, help_text='Ative para usar o ambiente de testes da Efi. Desative para producao.', verbose_name='Modo Sandbox (Testes)')),
                ('certificado_pix', models.FileField(blank=True, help_text='Arquivo .pem gerado no painel da Efi para cobrar via PIX.', null=True, upload_to='efi/certificados/', verbose_name='Certificado PIX (.pem)')),
                ('chave_pix', models.CharField(blank=True, default='', help_text='Sua chave PIX registrada na conta Efi (CPF, CNPJ, email ou aleatoria).', max_length=100, verbose_name='Chave PIX cadastrada na Efi')),
                ('webhook_url', models.URLField(blank=True, default='', help_text='URL que a Efi chamara para notificar pagamentos. Ex: https://pvd.luizgustavo.tech/api/efi/webhook/', verbose_name='URL do Webhook')),
                ('ativo', models.BooleanField(default=False, help_text='Marque somente quando tiver preenchido todos os campos acima e testado.', verbose_name='Integracao Ativa')),
            ],
            options={
                'verbose_name': 'Configuracao Efi',
                'verbose_name_plural': 'Configuracao Efi',
            },
        ),
        migrations.CreateModel(
            name='PlanoEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, help_text='Valor acordado com o cliente para cobranca mensal.', max_digits=10, verbose_name='Valor Mensal (R$)')),
                ('dia_vencimento', models.PositiveIntegerField(default=10, help_text='Dia do mes em que a fatura vence (1 a 28).', verbose_name='Dia do Vencimento')),
                ('isento', models.BooleanField(default=False, help_text='Marque para empresas de teste ou parceiros que nao pagam.', verbose_name='Isento de Cobranca')),
                ('observacoes', models.TextField(blank=True, default='', help_text='Anotacoes internas sobre o acordo comercial.', verbose_name='Observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_assinatura', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Plano de Assinatura',
                'verbose_name_plural': 'Planos de Assinatura',
                'ordering': ['empresa__nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Ex: Mensalidade Maio/2026', max_length=200, verbose_name='Descricao')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('data_emissao', models.DateField(default=datetime.date.today, verbose_name='Data de Emissao')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('arquivo_boleto', models.FileField(blank=True, help_text='Anexe o arquivo PDF do boleto para envio ao cliente.', null=True, upload_to='assinaturas/boletos/', verbose_name='Boleto (PDF)')),
                ('comprovante', models.FileField(blank=True, help_text='Anexe o comprovante quando o cliente pagar.', null=True, upload_to='assinaturas/comprovantes/', verbose_name='Comprovante de Pagamento')),
                ('efi_charge_id', models.CharField(blank=True, default='', help_text='Preenchido automaticamente quando integrado com a Efi.', max_length=100, verbose_name='ID da Cobranca (Efi)')),
                ('efi_pix_txid', models.CharField(blank=True, default='', help_text='Preenchido automaticamente quando cobrado via PIX Efi.', max_length=100, verbose_name='TxID PIX (Efi)')),
                ('efi_boleto_url', models.URLField(blank=True, default='', help_text='URL do boleto gerado pela Efi.', verbose_name='Link do Boleto (Efi)')),
                ('efi_qrcode_pix', models.TextField(blank=True, default='', help_text='Payload do QR Code PIX gerado pela Efi.', verbose_name='QR Code PIX (Efi)')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-data_vencimento'],
                'unique_together': {('empresa', 'descricao')},
            },
        ),
    ]
