# Generated by Django 5.1.4 on 2026-05-27 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(blank=True, default='', help_text='Ex: smtp.gmail.com, smtp.office365.com', max_length=200, verbose_name='Servidor SMTP')),
                ('email_port', models.PositiveIntegerField(default=587, help_text='Geralmente 587 (TLS) ou 465 (SSL)', verbose_name='Porta SMTP')),
                ('email_user', models.CharField(blank=True, default='', help_text='Ex: cobranca@suaempresa.com.br', max_length=200, verbose_name='Email Remetente')),
                ('email_password', models.CharField(blank=True, default='', help_text='Senha do email ou App Password (Gmail requer App Password)', max_length=200, verbose_name='Senha / App Password')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Ative para a maioria dos provedores (porta 587)', verbose_name='Usar TLS')),
                ('nome_remetente', models.CharField(blank=True, default='PDV Cloud - Cobrancas', help_text='Nome que aparecera no email. Ex: PDV Cloud - Cobrancas', max_length=100, verbose_name='Nome do Remetente')),
                ('ativo', models.BooleanField(default=False, help_text='Marque somente apos configurar e testar os dados acima.', verbose_name='Envio de Emails Ativo')),
            ],
            options={
                'verbose_name': 'Configuracao de Email',
                'verbose_name_plural': 'Configuracao de Email',
            },
        ),
        migrations.RemoveField(
            model_name='planoempresa',
            name='valor_mensal',
        ),
        migrations.AddField(
            model_name='fatura',
            name='email_lembrete_enviado',
            field=models.BooleanField(default=False, verbose_name='Lembrete Enviado'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='email_recibo_enviado',
            field=models.BooleanField(default=False, verbose_name='Recibo Enviado'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('', 'Nao informado'), ('pix', 'PIX'), ('boleto', 'Boleto'), ('cartao', 'Cartao de Credito'), ('transferencia', 'Transferencia'), ('outro', 'Outro')], default='', max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='planoempresa',
            name='dias_antecedencia',
            field=models.PositiveIntegerField(default=7, help_text='Quantos dias antes do vencimento a fatura e gerada e o email de lembrete enviado.', verbose_name='Dias de Antecedencia'),
        ),
        migrations.AlterField(
            model_name='configefi',
            name='chave_pix',
            field=models.CharField(blank=True, default='', help_text='Sua chave PIX registrada na conta Efi.', max_length=100, verbose_name='Chave PIX cadastrada na Efi'),
        ),
        migrations.AlterField(
            model_name='configefi',
            name='webhook_url',
            field=models.URLField(blank=True, default='', help_text='URL que a Efi chamara para notificar pagamentos.', verbose_name='URL do Webhook'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='efi_boleto_url',
            field=models.URLField(blank=True, default='', verbose_name='Link Boleto (Efi)'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='efi_charge_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID Cobranca (Efi)'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='efi_pix_txid',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='TxID PIX (Efi)'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='efi_qrcode_pix',
            field=models.TextField(blank=True, default='', verbose_name='QR Code PIX (Efi)'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)'),
        ),
        migrations.CreateModel(
            name='ItemFatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descricao')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='assinaturas.fatura', verbose_name='Fatura')),
            ],
            options={
                'verbose_name': 'Item da Fatura',
                'verbose_name_plural': 'Itens da Fatura',
            },
        ),
        migrations.CreateModel(
            name='ItemPlano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Ex: Sistema PDV, Bipador, Impressora, Manutencao', max_length=200, verbose_name='Descricao')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('recorrente', models.BooleanField(default=True, help_text='Sim = cobra todo mes. Nao = cobra apenas uma vez no proximo mes.', verbose_name='Cobranca Mensal?')),
                ('cobrado', models.BooleanField(default=False, help_text='Para itens de cobranca unica. Marca automaticamente apos gerar a fatura.', verbose_name='Ja Cobrado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='assinaturas.planoempresa', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Item do Plano',
                'verbose_name_plural': 'Itens do Plano',
                'ordering': ['-recorrente', 'descricao'],
            },
        ),
    ]
