# Generated by Django 5.1.4 on 2026-05-18 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelaFiado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_juros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
            ],
            options={
                'verbose_name': 'Parcela Fiado',
                'verbose_name_plural': 'Parcelas Fiado',
                'ordering': ['vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ContaFiado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Limite de Crédito (R$)')),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Devedor (R$)')),
                ('juros_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Juros Mensal (%)')),
                ('juros_atraso', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Juros Atraso (%)')),
                ('multa_atraso', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa Atraso (R$)')),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_fiado', to='clientes.cliente', verbose_name='Cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Conta Fiado',
                'verbose_name_plural': 'Contas Fiado',
                'ordering': ['cliente__nome'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoFiado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago (R$)')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao', 'Cartão')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Pagamento Fiado',
                'verbose_name_plural': 'Pagamentos Fiado',
                'ordering': ['-created_at'],
            },
        ),
    ]
