# Generated by Django 5.1.4 on 2026-05-18 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoCaixa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('abertura', models.DateTimeField(auto_now_add=True, verbose_name='Abertura')),
                ('fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Fechamento')),
                ('valor_abertura', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Abertura (R$)')),
                ('valor_fechamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Fechamento (R$)')),
                ('total_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_dinheiro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cartao_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cartao_debito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fiado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_troco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sangrias', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_suprimentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('divergencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], default='aberta', max_length=20)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Sessão de Caixa',
                'verbose_name_plural': 'Sessões de Caixa',
                'ordering': ['-abertura'],
            },
        ),
        migrations.CreateModel(
            name='Suprimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('motivo', models.TextField(verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Suprimento',
                'verbose_name_plural': 'Suprimentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sangria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Sangria',
                'verbose_name_plural': 'Sangrias',
                'ordering': ['-created_at'],
            },
        ),
    ]
