# Generated by Django 5.1.4 on 2026-05-18 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caixa', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sangria',
            name='operador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessaocaixa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='sessaocaixa',
            name='operador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_caixa', to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='sessaocaixa',
            name='pdv_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.pdvterminal', verbose_name='Terminal PDV'),
        ),
        migrations.AddField(
            model_name='sangria',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sangrias', to='caixa.sessaocaixa', verbose_name='Sessão'),
        ),
        migrations.AddField(
            model_name='suprimento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='suprimento',
            name='operador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suprimento',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suprimentos', to='caixa.sessaocaixa', verbose_name='Sessão'),
        ),
    ]
