# Generated by Django 5.1.4 on 2026-05-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaocaixa',
            name='local_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID Local PDV'),
        ),
    ]
