# Generated by Django 5.1.4 on 2026-05-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nfc_uid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID do Cartão NFC'),
        ),
    ]
