# Generated by Django 5.1.4 on 2026-05-18 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token API')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('config_juros_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Juros Mensal (%)')),
                ('config_juros_atraso', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Juros Atraso (%)')),
                ('config_multa_fixa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa Fixa (R$)')),
                ('config_dias_tolerancia', models.IntegerField(default=0, verbose_name='Dias de Tolerância')),
                ('pix_chave', models.CharField(blank=True, max_length=100, verbose_name='Chave PIX')),
                ('pix_tipo', models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('aleatoria', 'Chave Aleatória')], max_length=20, verbose_name='Tipo Chave PIX')),
                ('pix_nome', models.CharField(blank=True, max_length=100, verbose_name='Nome Beneficiário PIX')),
                ('pix_cidade', models.CharField(blank=True, max_length=50, verbose_name='Cidade PIX')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='PDVTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('identificador', models.CharField(help_text='Ex: PDV-001', max_length=20, verbose_name='Identificador')),
                ('nome', models.CharField(blank=True, help_text='Ex: Caixa Principal', max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ultimo_sync', models.DateTimeField(blank=True, null=True, verbose_name='Último Sync')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminais', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Terminal PDV',
                'verbose_name_plural': 'Terminais PDV',
                'ordering': ['identificador'],
                'unique_together': {('empresa', 'identificador')},
            },
        ),
    ]
