# Generated by Django 5.1.4 on 2026-05-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='config_impressao_tamanho',
            field=models.CharField(choices=[('80mm', 'Térmica 80mm (Padrão)'), ('58mm', 'Térmica 58mm (Pequena)'), ('a4', 'A4 (Folha Inteira)')], default='80mm', max_length=10, verbose_name='Tamanho do Papel de Impressão'),
        ),
    ]
