# Generated by Django 5.1.4 on 2026-05-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_config_impressao_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='endereco_bairro',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco_cep',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco_cidade',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco_complemento',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco_numero',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco_rua',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Rua/Logradouro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco_uf',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='UF'),
        ),
    ]
