# Generated by Django 5.1.4 on 2026-05-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_endereco_bairro_empresa_endereco_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email_faturamento',
            field=models.EmailField(blank=True, help_text='E-mail que receberá os avisos e boletos da assinatura do PDV Cloud', max_length=254, verbose_name='E-mail de Faturamento'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail Principal'),
        ),
    ]
