# Generated by Django 5.1.4 on 2026-05-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_email_faturamento_alter_empresa_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='mp_access_token',
            field=models.CharField(blank=True, default='', help_text='Token de produção do Mercado Pago. Obtido em: mercadopago.com.br/developers/panel. Usado pelos PDV locais para gerar PIX de vendas.', max_length=300, verbose_name='Access Token Mercado Pago'),
        ),
    ]
